pycam/networking/FTP.py

Bug fix for EOFError thrown in FTP file transfer

Catching EOFError in FTP

---

pycam/scripts/clouduploaders/dropbox_io.py

Now can see the folder (i.e. camera) the data is downloaded to/from

Small update to print information on data download

---

pycam/so2_camera_processor.py
pycam/tests/test_pyplis_worker.py
requirements.txt

Closes #29 
Adds test for this function/method
Adds new dependency `parameterized` to parameterize unit test

Fix buffer size

---

pycam/gui/figures_analysis.py

Fix error bar zorder

---

pycam/gui/cfg.py
pycam/gui/misc.py
pycam/gui/network.py
pycam/networking/sockets.py
pycam/scripts/pycam_masterpi.py
pycam/setupclasses.py

Resolves #50. But this led me to realise that later sockets don't work properly (#56). This update isn't really that useful on its own until #56 is fixed, but I wanted to create the update anyway.

External sock port update

---

pycam/gui/cfg.py
pycam/gui/misc.py
pycam/gui/network.py
pycam/networking/sockets.py
pycam/scripts/pycam_masterpi.py
pycam/setupclasses.py

Reverts twVolc/PyCamPermanent#57
Didn't mean to merge to master. Too tired...

Revert "External sock port update"

---

pycam/doas/ifit_worker.py

Instead of using ifit_ld Analyser, I can now use the ifit  Analyser having updated the plume_gas flag for SO2 to be True.

Using Analyser from ifit now

---

pycam/gui/figures_analysis.py
pycam/so2_camera_processor.py

Flow nadeau plume speed work. I've tried to make gather_vars() compatible with the new config.yml style

Flow nadeau

---

pycam/so2_camera_processor.py

Unreachable else conditions in `corr_light_dilution`

---

pycam/conf/processing_setting_defaults.yml
pycam/gui/figures_analysis.py
pycam/gui/menu.py
pycam/so2_camera_processor.py

Initial error fixed
FOV radius checked
`fix_fov` parameters added to config sp they can now be saved and loaded from config files

Fix for FIxed FOV option

---

pycam/so2_camera_processor.py

Update output dir at start of run

---

pycam/gui/figures_analysis.py
pycam/io_py.py
pycam/so2_camera_processor.py

Re-wrote the code to save the emission rates to a csv.
Now starts by converting the existing `EmissionRates` object to a dataframe, and then performing all the subsequent operations on that.
Maybe the `emis_cols` dictionary could be in a better place though?

Change units and column headings for output files

---

pycam/gui/figures_analysis.py
pycam/gui/figures_doas.py
pycam/gui/menu.py
pycam/gui/misc.py
pycam/tests/archive/test_utils.py
pycam/tests/test_utils.py
pycam/utils.py

This moves the code for truncating long paths used throughout the code into a single function, adds some error conditions, and adds tests for that function.

Add truncate path

---

pycam/doas/doas_worker.py
pycam/doas/ifit_worker.py

Fixes #118 
See issue for more details.

Reset stray_pix values on `doas_worker.dir_load()`

---

pycam/conf/processing_setting_defaults.yml
pycam/gui/menu.py
pycam/so2_camera_processor.py
pycam/tests/transfer.py

Adds menu items for directory-watching based RTP, and config item for setting the `watching_dir`.
Not sure if these are where you want them in the GUI if not I'm happy to move them.
This is nowhere near complete, and will need additions to make sure that RTP works properly (e.g. setting the output dir, adding the ability to change the watching_dir in the GUI, etc). These are all in progress but I wanted to get this merged first as the rest builds on it.

Add Real-Time Processing Menu items

---

pycam/conf/processing_setting_defaults.yml
pycam/gui/menu.py
pycam/so2_camera_processor.py
pycam/tests/transfer.py

Same as before but actually merging to the correct branch this time

Add Real-time processing menu items 

---

pycam/gui/menu.py
pycam/io_py.py
pycam/so2_camera_processor.py

Fixes #180 by applying config file in gather_vars() of SaveFrame()

SO2 image save fix

---

pycam/gui/figures_doas.py

Fixes #153. Updates spectrometer plot y-limits.

Update plot y-limits

---

pycam/gui/figures_analysis.py

Fixes #149 where the plume velocity frame wouldn't update once it had been closed and reopened.

Fixes plume velocity update bug

---

pycam/so2_camera_processor.py

Fixes saving of calibrated images

---

pycam/doas/doas_worker.py
pycam/doas/ifit_worker.py
pycam/doas/spec_worker.py
pycam/gui/cfg.py
pycam/gui/menu.py
pycam/gui/pycam_gui.py
pycam/io_py.py
pycam/so2_camera_processor.py
pycam/tests/fauxPiCam/README.md
pycam/tests/fauxPiCam/docker-compose.yaml
pycam/tests/fauxPiCam/dockerfile
pycam/tests/fauxPiCam/entrypoint.sh
pycam/tests/fauxPiCam/proftpd.conf

Closes #123 
Data is now saved incrementally.
For Emissions and DOAS calibration this is first saved after calibration has been run and the emissions data has been updated, and then saved for each individual time point after that.
For DOAS data this will be saved for each individual point as it's processed.

Issue 123/change data save frequency

---

pycam/io_py.py

This should fix #171 
The only thing that may need considering is whether the number of retries and/or the length of the sleep is long enough to get a file that is slow to transfer.

fix load spectrum permission error

---

pycam/gui/figures_analysis.py

This does a reasonable job of fixing #208. I think to some extent this is never going to be perfect as it's just that the calbirated images can look horrednous on cloudy days with a poor calibration line. They seem to jump in discrete steps in bands across the image, and these steps can be absolutely tiny.

Issue 208/so2 fig scaling

---

pycam/gui/figures_analysis.py
pycam/gui/figures_cam.py
pycam/gui/figures_doas.py

Spinboxes now execute a command when a value is entered and then focus is moved away (e.g. by clicking on next box).
Try it out and see if you're happy with the change for the wavlength start/end boxes and if so I can add it to other places too.

Fix Doas figure spinboxes

---

pycam/gui/cfg_menu_frames.py
pycam/gui/figures_analysis.py
pycam/gui/menu.py
pycam/gui/pycam_gui.py
pycam/so2_camera_processor.py

Moved all frames into a single window/option - fixes #145.
TODO add a scrollbar for optical flow window (it goes off the bottom of the screen so can't click Apply)

Moved all velocity settings to single frame

---

pycam/gui/figures_analysis.py

Add points for Analysis time series plots

---

README.md

closes #215 
More info can be found in the issue

Update readme to move away from Anaconda installer

---

pycam/conf/processing_setting_defaults.yml
pycam/doas/doas_worker.py
pycam/doas/ifit_worker.py
pycam/doas/spec_worker.py
pycam/gui/acquisition.py
pycam/gui/figures_analysis.py
pycam/gui/menu.py
pycam/gui/pycam_gui.py
pycam/networking/FTP.py
pycam/so2_camera_processor.py

Adds element for setting:
- FTP output directory
- Watching directory
I copied the layout used for setting post processing directories but if you have other ideas about where these should go I'm happy to change it.
closes #189

Add GUI elements for setting real time processing directories

---

pycam/conf/processing_setting_defaults.yml
pycam/doas/doas_worker.py
pycam/doas/ifit_worker.py
pycam/doas/spec_worker.py
pycam/gui/figures_doas.py
pycam/gui/menu.py
pycam/gui/pycam_gui.py
pycam/so2_camera_processor.py

Move wavelength doas parameters to config file

---

pycam/gui/figures_analysis.py

Add option to select file path, and renamed method to reflect more general nature.
fixes #246

fix calibration path selection in GUI 

---

.github/workflows/restrict-PR-target.yml

action seems to have moved to different owner, updated the workflow file to reflect that

update workflow action owner

---

pycam/gui/misc.py
pycam/setupclasses.py
requirements.txt

closes #251 
Updates version details.
Updates repo locations.

Preparations for 2024.11 release

---

pycam/so2_camera_processor.py

Issue 278 nearest dark

---

pycam/conf/processing_setting_defaults.yml
pycam/doas/cfg.py
pycam/doas/ifit_worker.py
pycam/gui/figures_doas.py
pycam/gui/menu.py
pycam/so2_camera_processor.py

This PR allows the species reference files and values to be changed in the configuration file rather than just hard-coded in [cfg.py](https://github.com/volcanotech-sw/PyCamPermanent/blob/71a3ae6ecca7fa9331ddaf03adfa84bcdcc50f89/pycam/doas/cfg.py#L19). The default is set to `SO2_293K.txt`
It's my first time editing anything to do with the config so let me know if I've missed any steps @ubdbra001 🙂.

Species config

---

pycam/so2_camera_processor.py

Second part of adding logging to PyCam, this time focussing on `PyplisWorker`. Initially this is just for the console logs, I'll add file logging later.
As before it would be good to get feedback on the levels I've selected for these messages. If you do spot anything else that looks odd then do give me a shout!

Add logging for pyplis module

---

pycam/conf/config.txt
pycam/gui/menu.py
pycam/gui/network.py
pycam/networking/ssh.py
pycam/scripts/remote_pi_run_pycam.py
pycam/setupclasses.py

Add ssh_port config.txt entry
