volcanotech-sw/PyCamPermanent

pycam/gui/figures_analysis.py
pycam/so2_camera_processor.py

Fixes #16 
Plot looks like this (although the right y-axis has the label "R squared")
Two thoughts:
1. Do you want to change the label for the left y-axis?
- Fit 1st order doesn't mean much to me, but it may be fine for you
2. Do you want to set limits for the right y-axis? 
- To me the automatically selected limits of this axis makes small changes in R squared look bigger than they are
- Could set the axes so they have a specific lower bound that allows you to see true dips in fit (e.g. pulling a number from a hat: 0.7)

Add calibration fit statistics

---

pycam/conf/processing_setting_defaults.yml
pycam/doas/ifit_worker.py
pycam/gui/figures_analysis.py
pycam/gui/figures_doas.py
pycam/gui/pycam_gui.py
pycam/so2_camera_processor.py

Added new iFit functionality:
1.  Can manually shift the spectrum prior to processing - useful for some spectrometers where shifts in calibration are quite large and the iFit built in shift doesn't seem to deal with the issue sufficiently
2. Added functionality to manually set the light dilution factor (LDF) under which all spectra will then be processed. Useful if a location displays quite consistent LDFs - processing this way drastically speeds up processing relative to performing a full LDF calculation for each spectrum.

Ifit shift updates

---

pycam/so2_camera_processor.py

Small fix to make sure that load_cal_series is only called when the calibration type is set accordingly

Cal_series_path_fix

---

pycam/gui/figures_analysis.py

Changes what the 'OK' button does in the 'Background model' window, so that the BG model selected is saved and window closed after pressing 'OK'.
Checks to see if the model selected is the same as currently used/loaded.
- If yes then it just closes the window
- If no, then it runs the model (updating the settings, and plot in analysis window) and then closes the window
__NB:__ This only checks that the BG model selection is the same, if other settings are changed but the BG model isn't then these changes will be lost.
Also, changes the label of the 'Run' button to 'Preview'

Fix bgmode switch

---

pycam/gui/figures_analysis.py
pycam/so2_camera_processor.py

Partly addresses #75 by making it possible to close the DOAS FOV window, but it doesn't identify the root cause of that slow-down which may be useful for the time-series plots too; so I don't think this pull request should close the issue.

DOAS FOV plot can now be closed

---

pycam/gui/figures_analysis.py

update_vars() for DOAS FOV had a bug that was setting the y pixel coordinate to be be disaplyed as the x coordinate in the GUI i.e. both x and y were showing the x pixel value

Fixed fixed FOV GUI bug

---

pycam/so2_camera_processor.py

Drops calibration series attribute when "preloaded" not selected, and checks to ensure that the calibration type is "preloaded" when saving the calibration.
Fixes #105

Checks to ensure correct calibration_series is saved

---

pycam/gui/figures_analysis.py
pycam/so2_camera_processor.py

Fixes #120 
Removed the rotation from the GUI code and adjusted the backend code to calculate the coordinates properly.
Added getter/setter for `nadeau_line_orientation` attribute. Not needed strictly speaking, but I find constraining the angle of the orientation useful.
Looks like the primary issue was the y coordinate calculation, sign needed to be inverted to account for the fact that 0 at the top of the image.
Also, adjusted the `calc_line_orientation()` function to deal with this change.

Issue 120/nadeau config fix

---

pycam/doas/doas_worker.py
pycam/doas/ifit_worker.py
pycam/gui/figures_doas.py
pycam/gui/menu.py
pycam/gui/misc.py
pycam/gui/windows.py

Fixes #116 
This adds a frame to display the currently specified `spec_dir` for DOAS
It should also ensure that the updated `spec_dir` (either thought the GUI or a config) is saved to a new config properly.
Not sure if it resolves the previously discussed reset of the Dark Spectra/ Spectra directories, so give it a try and if it doesn't let me know.

Issue 116/display and save config

---

pycam/gui/figures_doas.py

Fixes #142 by setting the ILS frame flag to False when the calibration frame is closed down.
This also simultaneously fixed a bug I found that meant you could open an unlimited number of calibration frames simultaneously. Now instead only one can be opened - the frame is brought back to the front if hidden and a new attempt to open it is made.

Fixes #142

---

pycam/so2_camera_processor.py

Fixing bug where saved SO2 images were picked up by the directory watcher and attempted to be processed. They are now ignored.

SO2 image directory watcher bug fix

---

pycam/conf/processing_setting_backup.yml
pycam/conf/processing_setting_defaults.yml
pycam/gui/figures_analysis.py
pycam/gui/menu.py
pycam/so2_camera_processor.py

Fixes https://github.com/twVolc/PyCamPermanent/issues/198 and pretty much acheives https://github.com/twVolc/PyCamPermanent/issues/174 - although saving as images rather than a video. The figure is saved in whatever state the analysis window is currently in, so the user will need to select ppmm in that window for ppmm to be saved.
Future development should make the save option possible so if ppmm is chosen the analysis window is forced to ppmm once a calibration is avaliable, and then these figures begin to be saved.

Save matplotlib so2 img

---

pycam/doas/ifit_worker.py
pycam/doas/spec_worker.py
pycam/so2_camera_processor.py

Hopefully fixes https://github.com/twVolc/PyCamPermanent/issues/203 by adding a lock which is acquired by `PyplisWorker` and `IFitWorker` when trying to access `IFitWorker.results`.
I currently have this running on the Merapi machine, but the camera has stopped for the day, so we won't find out if #203 is hit again until at least tomorrow. If I've understood the error correctly this should solve it though. Fingers crossed...

Issue 203/add doas lock

---

pycam/so2_camera_processor.py

Should fix #169 using the approach discussed in the issue.
Set-up to attempt to load the image a limited number of times before throwing an error and skipping to the next image.
As with #194 there may be some discussion around the number of attempts and how long to wait between attempts, the numbers I picked were out of thin air.

Issue 169/handle img load error

---

pycam/so2_camera_processor.py
pycam/tests/transfer.py

Fixes #170 
I opted for the second option. Let me know fi you'd like me to add the first option in this PR too.
This also updates the transfer script so that transfers with missing spectra can be simulated. Previously it would have just skipped the images for that timepoint if there was no spectra. It should also be able to handle/simulate cases where one of the image pair is missing too.

Stop waiting to update doas calibration if newer data point appears

---

pycam/so2_camera_processor.py

If the user requests a ppm.m figure save but there is no calibration data available the figure will now save in its tau form, rather than just not saving the figure. When calibration data become available the figure then shifts to ppm.m as requested.

Fig tau now plotted if ppmm not available

---

.github/workflows/restrict-PR-target.yml

This adds an action to the repo that will fail if a PR to the `master` branch doesn't contain `dev` at the start.
It won't run for this PR and likely won't run properly until it is incorporated in the `master` branch, but I think doing it this way is okay because a PR into `master` is forthcoming (and easier than faffing about adding commits back to the `dev` branch)

add action restricting PR target

---

.github/workflows/restrict-PR-target.yml

Missing rule for merging into `dev` causing failures.
This should fix that 🤞

update PR check rules again

---

pycam/doas/ifit_worker.py
pycam/so2_camera_processor.py

@ubdbra001 if you're able to test this, both in terms of the standard tests to make sure I haven't broken the calculations in some way and in terms of RTP work to see if it seems to run smoothly, that would be great. If I understand correctly, you don't seem to have encountered the #209 error as frequently as we did in Indonesia, so perhaps this isn't going to be a water tight way of checking that it has both removed the issue and not incorporated other annoying isues as before. I think the best we can do is check it on a large amount of data in the RTP mode, to see what happens.
Essentially all I've done is breakout the lock acuqisition into bitsize chunks within `PyplisWorker.update_doas_calibration()` rather than holding the lock for the entirety of the method execution. This should …

Issue 209/new fix

---

.github/workflows/restrict-PR-target.yml

I think this will finally work now.
Apparently `/` doesn't fall under the wildcard (`*`)

PR branch checker - Third time lucky

---

pycam/conf/processing_setting_defaults.yml
pycam/so2_camera_processor.py

This should close #151 
When the config is saved the metadata files saved alongside it are recorded in the file using relative paths (effectively just filenames)
When a config is loaded the list of path parameters are checked and expanded to absolute paths if needed. Not sure if the list of path params are best at the start of `so2_camera_processor.py` or somewhere else. Happy to move them if you think that makes sense. 
I think it captures all the edge cases around loading and saving paths, but if, during testing, you spot any that I haven't caught do let me know.

Change metadata file paths in config to be relative

---

pycam/exceptions.py
pycam/gui/figures_analysis.py
pycam/gui/menu.py
pycam/so2_camera_processor.py

This is an update to PR #193. I rebased the branch on the latest dev commit and resolved the merge conflict, but couldn't push the changes to the open PR (due git history differences).
As discussed in #193 I've added an exception to Pyplisworker and moved the error box to the GUI, which is shown when the exception is raised and caught.
I've also added a warning in the GUI if the user tries to select the preloaded calibration but without specifying a valid file path. It will keep the user there until they provide a valid file or choose a different calibration type.
The last thing that may need resolving is when a user tries to load a config file where `cal_type_int` is 3 but the filename provided doesn't exist. Currently this throws an error but is not handled anywhere. I think it fits in …

Issue 140/preloaded cal rtp

---

pycam/gui/menu.py
pycam/gui/pycam_gui.py
pycam/so2_camera_processor.py

Fixes #141
This makes sure that the paths specified in the config file actually exist. If not there are two different behaviours depending on when the config file is being loaded:
1. If it is the when PyCam starts (i.e. the default config) then it will fall back to the config file that is supplied with PyCam, and show a warning box once the GUI has loaded (it will also print a warning in the console).
2. If it is when a user config is loaded, then it will display an error box and will keep the currently loaded config. If running without a GUI it will just throw an exception.
The actual messages may need some work.

Provide feedback when config loading fails

---

pycam/networking/FTP.py

Moves the `retrieve_schedule_files()` method outside of open_connection so it's not run every time the connection is opened or tested. Fixes #182

Move the `retrieve_schedule_files()` method

---

pycam/so2_camera_processor.py

fixes #167 
For `flow_glob` mode, while `vel_glob` is not established the default behaviour in `calculate_emission_rate()` is to  save the col densities, etc to a buffer and add empty values to the results, then `get_cross_corr_emissions_from_buff()` go back through the buffer to process the results. But it appends the results from the buffer instead of updating them. 
This commit the code so that in this case, if a timepoint already exists in the results, then just update the value instead of appending it. 
I don't think the code appending the results is needed, but left anyway just in case there is a case where the value will need to be appended from the buffer.

Don't save empty rows in `line_total` `flow_glob` output

---

pycam/so2_camera_processor.py

This fixes #237
When there is an image pair without an associated spectra timepoint the calibration file will include blank columns for the image/spectra data (tau, cd, etc) and reuse the last calibration values (coeff, MSE, etc).
It will only do this once the calibration has done it's initial run, prior to this it will just drop the missing timepoints. This is to maintain consistency between the "fov find" and "fov fixed" approaches.
Emission results are consistent with dev branch results.

Add blank data for missing spectra timepoints

---

pycam/gui/figures_analysis.py
pycam/gui/pycam_gui.py

Fixes #213.
Options now available to toggle the display of different plume speeds off and on in the time series figure. And these options are disabled if a certain plume speed algorithm is not currently being generated.

Issue 213/toggle plumespeeds

---

pycam/io_py.py
pycam/so2_camera_processor.py

Fixes #233 
Need to:
Adds function to calculate ICA_mass for each PCA/ICA line, plus the total.
Adds the results to the emission rate output files.
Some reorganisation of `calculate_emission_rates()` to simplify code.
Test skipped until after separation of config methods from `PyplisWorker`

add function for calculating ICA masses

---

pycam/so2_camera_processor.py

Fixes #73
Fixes #94 
I think these changes address the discrepancies between post-processing runs where there is an FOV search, the FOV is fixed, and a pre-loaded calibration is used. The results include all time points (except the last one), and the results for these tome points are equivalent to 6 decimal places (which I think is mg/s).
The only remaining discrepancy is with the full calibration files, but from what I can tell these are very small differences, and do not affect the final output. I think it would be possible to iron out these, but If you're happy with the emissions outputs being identical then it's probably not worth the effort.

Ensure FOV search, fixed FOV, and preloaded calibration produce identical output

---

pycam/gui/cfg.py
pycam/networking/FTP.py
pycam/utils.py

This PR changes `StorageMount` to have a class variable that contains the location of the mounted SSD on the Raspberry Pi. This lets the `FTPClient` class access this information without creating an instance of `StorageMount` when loading the GUI.
This PR addresses issue #262  where loading the GUI prompted for a password in `sudo`, which occurred as a result of  `StorageMount.__init__()` calling `StorageMount.find_dev()`. `find_dev()` is only applicable to running on the Raspberry Pi and should not be executed by the GUI.

change mount path to StorageMount class variable (#262)

---

requirements.txt

The win32 API is used as part of the directory watching code. This looks to have conditional logic in place for if the code is running on Windows and should use pywin32 or if it's running on Linux and should use pyinotify instead.
https://github.com/volcanotech-sw/PyCamPermanent/blob/71a3ae6ecca7fa9331ddaf03adfa84bcdcc50f89/pycam/directory_watcher.py#L37-L52
This PR makes the pywin32 dependency similarly conditional, so that `pip install -r requirements.txt` can be run on Linux as suggested in #254.
I've tested this on Ubuntu Linux 20.04 and Windows 10 and had the expected behaviour on Linux with pip reporting `Ignoring pywin32: markers 'sys_platform == "win32"' don't match your environment` and pywin32 being installed on Windows and being able to run `import win32` without error.

only require pywin32 on windows

---

pycam/so2_camera_processor.py

Goes some way to removing the likelihood of #277 although this isn't a direct fix of that.
Clear sky images are now flagged as dark subtracted whether or not a dark image can be found for their shutter speed. A warning is raised if a dark image can't be found. This is in line with how plume images are dealt with if a dark image can't be found. 
More consideration should be given to #278 so that, rather than not subtracting any dark image, the nearest shutter speed dark image is subtracted. This would be optimal.
This PR also makes cell calibration more flexible with lack of dark images. Again, printing a warning rather than failing if dakr images aren't present.

Issue 278 dark subtraction

---

pycam/conf/processing_setting_defaults.yml
pycam/doas/ifit_worker.py
pycam/doas/spec_worker.py
pycam/gui/figures_doas.py
pycam/gui/menu.py
pycam/gui/pycam_gui.py
pycam/so2_camera_processor.py

@ubdbra001 The only thing I haven't quite got sorted is the warning box doesn't seem to pop up if you load a config file that doesn't have `include_ils_fit` attribute in it. Can you think why this might be?
Other than that this works well - you can toggle the ILS fit on and off in Prcoessing Settings > Calibration > DOAS calibration using the check box next to the ILS figure. DOAS results are slightly different if you process the default sequence with this on and off.

Issue 275 fit ils

---

pycam/gui/figures_analysis.py

Fixes #266
When ICA line used for flow Nadeau line auto generation is removed the GUI will revert back to ICA line 1.
This PR also limits the spinbox options to available lines, and adds the ability to type the ICA line number and click off or press the return key to change the line used.

Use ICA line 1 for Nadeau line auto-generation when current ICA line deleted

---

pycam/directory_watcher.py
pycam/doas/doas_worker.py
pycam/doas/ifit_worker.py
pycam/doas/spec_worker.py
pycam/gui/figures_doas.py
pycam/logging/logging_tools.py
pycam/so2_camera_processor.py
requirements.txt

This is the first part of adding logging, and focussed on `SpecWorker` and `IFitWorker`.
As it stands these are logging to the console, and also writing to a general logging file (found in your home directory + `/pycam_logs/root.log`, e.g.: `C:\Users\Daniel\pycam_logs\root.log`), but everything is being written at the `INFO` level (see [here](https://docs.python.org/3.12/library/logging.html#logging-levels) for more details about the levels).
You don't want all of these messages to appear in the console, to do this I can either:
1. Set the messages you want to hide to the `DEBUG` level
2. Set the level filter to `WARNING` and set the messages you want to keep to warning
3. Set up a level between `INFO` and `WARNING`, specifically for processing related messages you want to see in the …

Add logging to DOAS related modules 
